### ISSUE TITLE
[SSL error] alpine 3.7 image does not support my self certificate

### ISSUE THREAD

**Issue by bastienbc** [drone/drone-git#20]
Hi,

I am currently studying the possibility of using drone in the company i am working for, and i have been stuck for moment now on a certificate issue.

We use an on-premise bitbucket server with a self certificate.
The cloning part of the drone pipeline was telling me that it could not verify the certificate, so I simply put this in the DRONE_RUNNER_VOLUMES variable in the agent:
```
  environment:
  - DRONE_RUNNER_VOLUMES=/etc/ssl/certs/:/etc/ssl/certs
```

After that the docker-git container said that the certificate had expired, which cannot be true.
During my tests, I successfully pull the git project from the agent itself, so I checked and the only difference I found is that the agent is from alpine:3.9 and docker-git is from alpine:3.7

I reduced the test to a simple curl request from he alpine docker itself:
```
$ docker run -it --rm -v /etc/ssl/certs/:/etc/ssl/certs:ro  --entrypoint /bin/sh alpine:3.9 -c 'apk add curl 2>&1 >/dev/null && curl -sSLI bitbucket.*******.***** > /dev/null'
# no result means no error from curl
$ docker run -it --rm -v /etc/ssl/certs/:/etc/ssl/certs:ro  --entrypoint /
bin/sh alpine:3.7 -c 'apk add curl 2>&1 >/dev/null && curl -sSLI bitbucket.********.***** > /dev/null'
curl: (51) SSL certificate verify result: certificate has expired (10)
```

I can do a workaround this issue by disabling cloning, and by making my own clone image, but I would like to use the drone ci without this complication as soon as possible, to prove its power to my colleagues ^^.

**Comment by bradrydzewski** [comment]
:wave: hey there, per our [issue template](https://raw.githubusercontent.com/drone/drone/master/.github/issue_template.md), for end-user support please use one of our support channels, such as our [chatroom](https://gitter.im/drone/drone) or our [mailing list](https://discourse.drone.io).
