### ISSUE TITLE
Issue on pull request clone with github

### ISSUE THREAD

**Issue by AlbertoBarba** [drone/drone-git#22]
https://github.com/drone/drone-git/blob/1af95e77567b713bf66211955b1eedbfa2024c8c/posix/clone-pull-request#L19

Fetching the refs of a PR from github often causes the CI to failure due to the following error:
```
+ git merge COMMIT-HASH
merge: COMMIT-HASH - not something we can merge
```
Having it running successfully requires us to restart the build after a couple of minutes.

I tried to introduce a small change in a fork so that the plugin fetches the `DRONE_COMMIT_SHA` instead of the `DRONE_COMMIT_REF` and it seems to run flawlessly. Would you accept a PR with the change or in your opinion it could cause problems?

**Comment by dimastark** [comment]
Same to me, very annoying issue. @AlbertoBarba Did you push docker image to registry? Can you share, please?

**Comment by AlbertoBarba** [comment]
@dimastark sure, u can find it here https://hub.docker.com/r/prontopro/drone-git
